### ISSUE TITLE
from guiUtil.template import pieChart, table

### ISSUE THREAD

**Issue by Eric-coder** [leixingyu/mayaAsciiParser#1]
ImportError: cannot import name 'table' from 'guiUtil.template'

**Comment by PetrMaxa** [comment]
I have same problem

**Comment by leixingyu** [comment]
fixed in this commit: https://github.com/leixingyu/mayaAsciiViewer/commit/669d6f349d7ee43be03aabf3cfdabdbd3f3f8bd4
